const fs = require('fs');
const pkg = require('../package.json');

const versionFile = `// auto-generated by inject-version.js
export const VERSION = '${pkg.version}';
`;

fs.writeFileSync('./src/version.ts', versionFile);
console.log('Injected version', pkg.version);
